export const defaultSkins = [
  // ========== 经典配色风格 ==========
  {
    id: 'default',
    name: '默认皮肤',
    nameEn: 'Default Skin',
    preview: '',
    isDefault: true,
    isSystem: true,
    variables: {
      '--primary-color': '#409eff',
      '--secondary-color': '#67c23a',
      '--accent-color': '#e6a23c',
      '--bg-color': '#ffffff',
      '--bg-color-secondary': '#f5f7fa',
      '--text-color': '#303133',
      '--text-color-secondary': '#606266',
      '--text-color-placeholder': '#909399',
      '--border-color': '#dcdfe6',
      '--border-color-light': '#e4e7ed',
      '--shadow': '0 2px 12px 0 rgba(0, 0, 0, 0.1)',
      '--shadow-hover': '0 4px 16px 0 rgba(0, 0, 0, 0.15)',
      '--radius': '8px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'var(--bg-color)',
      '--category-title-scale': '1'
    }
  },
  {
    id: 'dark',
    name: '深色皮肤',
    nameEn: 'Dark Skin',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#409eff',
      '--secondary-color': '#67c23a',
      '--accent-color': '#e6a23c',
      '--bg-color': '#1d1e1f',
      '--bg-color-secondary': '#141414',
      '--text-color': '#e5eaf3',
      '--text-color-secondary': '#cfd3dc',
      '--text-color-placeholder': '#909399',
      '--border-color': '#4c4d4f',
      '--border-color-light': '#606266',
      '--shadow': '0 2px 12px 0 rgba(0, 0, 0, 0.3)',
      '--shadow-hover': '0 4px 16px 0 rgba(0, 0, 0, 0.4)',
      '--radius': '8px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'var(--bg-color)',
      '--category-title-scale': '1'
    }
  },

  // ========== 极简风格 ==========
  {
    id: 'minimal',
    name: '极简风格',
    nameEn: 'Minimal Style',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#000000',
      '--secondary-color': '#333333',
      '--accent-color': '#666666',
      '--bg-color': '#ffffff',
      '--bg-color-secondary': '#fafafa',
      '--text-color': '#1a1a1a',
      '--text-color-secondary': '#666666',
      '--text-color-placeholder': '#cccccc',
      '--border-color': '#e0e0e0',
      '--border-color-light': '#f0f0f0',
      '--shadow': 'none',
      '--shadow-hover': '0 2px 8px 0 rgba(0, 0, 0, 0.08)',
      '--radius': '4px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'transparent',
      '--category-title-scale': '1'
    }
  },

  // ========== 卡片风格 ==========
  {
    id: 'card',
    name: '卡片风格',
    nameEn: 'Card Style',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#ff6b6b',
      '--secondary-color': '#ee5a6f',
      '--accent-color': '#c44569',
      '--bg-color': '#fff5f5',
      '--bg-color-secondary': '#ffe3e3',
      '--text-color': '#2d3436',
      '--text-color-secondary': '#636e72',
      '--text-color-placeholder': '#b2bec3',
      '--border-color': '#fdcb6e',
      '--border-color-light': '#ffeaa7',
      '--shadow': '0 4px 20px 0 rgba(253, 203, 110, 0.15)',
      '--shadow-hover': '0 8px 30px 0 rgba(253, 203, 110, 0.25)',
      '--radius': '16px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'var(--bg-color)',
      '--category-title-scale': '1.05'
    }
  },

  // ========== 玻璃态风格 ==========
  {
    id: 'glass',
    name: '玻璃态风格',
    nameEn: 'Glass Style',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#00cec9',
      '--secondary-color': '#81ecec',
      '--accent-color': '#55efc4',
      '--bg-color': 'rgba(255, 255, 255, 0.85)',
      '--bg-color-secondary': 'rgba(255, 255, 255, 0.6)',
      '--text-color': '#2d3436',
      '--text-color-secondary': '#636e72',
      '--text-color-placeholder': '#b2bec3',
      '--border-color': 'rgba(255, 255, 255, 0.3)',
      '--border-color-light': 'rgba(255, 255, 255, 0.2)',
      '--shadow': '0 8px 32px 0 rgba(0, 206, 201, 0.25)',
      '--shadow-hover': '0 12px 48px 0 rgba(0, 206, 201, 0.35)',
      '--radius': '24px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'rgba(255, 255, 255, 0.4)',
      '--category-title-scale': '1'
    }
  },

  // ========== 新拟物风格 ==========
  {
    id: 'neumorphism',
    name: '新拟物风格',
    nameEn: 'Neumorphism',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#6c5ce7',
      '--secondary-color': '#a29bfe',
      '--accent-color': '#fd9644',
      '--bg-color': '#e8e8e8',
      '--bg-color-secondary': '#dcdcdc',
      '--text-color': '#2d3436',
      '--text-color-secondary': '#636e72',
      '--text-color-placeholder': '#a0a0a0',
      '--border-color': '#e8e8e8',
      '--border-color-light': '#dcdcdc',
      '--shadow': '8px 8px 16px #b8b8b8, -8px -8px 16px #ffffff',
      '--shadow-hover': '12px 12px 24px #b8b8b8, -12px -12px 24px #ffffff',
      '--radius': '20px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'var(--bg-color)',
      '--category-title-scale': '1'
    }
  },

  // ========== 渐变风格 ==========
  {
    id: 'gradient',
    name: '渐变风格',
    nameEn: 'Gradient Style',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#ff0080',
      '--secondary-color': '#7928ca',
      '--accent-color': '#ff4757',
      '--bg-color': '#667eea',
      '--bg-color-secondary': '#764ba2',
      '--text-color': '#ffffff',
      '--text-color-secondary': '#e0e7ff',
      '--text-color-placeholder': '#b8c6ff',
      '--border-color': 'rgba(255, 255, 255, 0.2)',
      '--border-color-light': 'rgba(255, 255, 255, 0.1)',
      '--shadow': '0 8px 32px 0 rgba(102, 126, 234, 0.37)',
      '--shadow-hover': '0 12px 48px 0 rgba(102, 126, 234, 0.5)',
      '--radius': '16px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'rgba(255, 255, 255, 0.15)',
      '--category-title-scale': '1.05'
    }
  },

  // ========== 圆润风格 ==========
  {
    id: 'rounded',
    name: '圆润风格',
    nameEn: 'Rounded Style',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#f39c12',
      '--secondary-color': '#fd7e14',
      '--accent-color': '#ff6b6b',
      '--bg-color': '#fffbf0',
      '--bg-color-secondary': '#fff3cd',
      '--text-color': '#1a1a1a',
      '--text-color-secondary': '#7f8c8d',
      '--text-color-placeholder': '#cfd8dc',
      '--border-color': '#ffeaa7',
      '--border-color-light': '#fed7aa',
      '--shadow': '0 6px 24px 0 rgba(251, 191, 36, 0.15)',
      '--shadow-hover': '0 12px 36px 0 rgba(251, 191, 36, 0.25)',
      '--radius': '24px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'var(--bg-color)',
      '--category-title-scale': '1'
    }
  },

  // ========== 暗黑科技风格 ==========
  {
    id: 'cyberpunk',
    name: '暗黑科技',
    nameEn: 'Cyberpunk',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#00ff41',
      '--secondary-color': '#00d9ff',
      '--accent-color': '#ff0055',
      '--bg-color': '#0a0a0a',
      '--bg-color-secondary': '#1a1a2e',
      '--text-color': '#00ff41',
      '--text-color-secondary': '#00d9ff',
      '--text-color-placeholder': '#666666',
      '--border-color': '#00ff41',
      '--border-color-light': '#1a1a2e',
      '--shadow': '0 0 20px 0 rgba(0, 255, 65, 0.5)',
      '--shadow-hover': '0 0 30px 0 rgba(0, 255, 65, 0.7)',
      '--radius': '2px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'var(--bg-color-secondary)',
      '--category-title-scale': '1'
    }
  },

  // ========== 柔和风格 ==========
  {
    id: 'soft',
    name: '柔和风格',
    nameEn: 'Soft Style',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#95a5a6',
      '--secondary-color': '#b2bec3',
      '--accent-color': '#dfe6e9',
      '--bg-color': '#f8f9fa',
      '--bg-color-secondary': '#edf2f7',
      '--text-color': '#2d3436',
      '--text-color-secondary': '#7f8c8d',
      '--text-color-placeholder': '#b2bec3',
      '--border-color': '#dfe6e9',
      '--border-color-light': '#edf2f7',
      '--shadow': '0 2px 8px 0 rgba(189, 195, 199, 0.12)',
      '--shadow-hover': '0 4px 16px 0 rgba(189, 195, 199, 0.2)',
      '--radius': '12px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'var(--bg-color)',
      '--category-title-scale': '1'
    }
  },

  // ========== 大卡片风格 ==========
  {
    id: 'large-cards',
    name: '大卡片风格',
    nameEn: 'Large Cards',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#3498db',
      '--secondary-color': '#2980b9',
      '--accent-color': '#1abc9c',
      '--bg-color': '#ffffff',
      '--bg-color-secondary': '#f8f9fa',
      '--text-color': '#2c3e50',
      '--text-color-secondary': '#7f8c8d',
      '--text-color-placeholder': '#bdc3c7',
      '--border-color': '#e0e0e0',
      '--border-color-light': '#ecf0f1',
      '--shadow': '0 4px 20px 0 rgba(52, 152, 219, 0.15)',
      '--shadow-hover': '0 8px 30px 0 rgba(52, 152, 219, 0.25)',
      '--radius': '16px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'var(--bg-color)',
      '--category-title-scale': '1',
      '--link-grid-columns': 'repeat(auto-fill, minmax(350px, 1fr))',
      '--link-grid-gap': '1.5rem',
      '--link-card-padding': '2rem',
      '--link-font-size': '1.375rem',
      '--link-description-font-size': '1rem',
      '--link-content-gap': '0.75rem',
      '--category-font-size': '1.75rem',
      '--category-margin-bottom': '2rem',
      '--link-card-max-width': 'none'
    }
  },

  // ========== 紧凑风格 ==========
  {
    id: 'compact',
    name: '紧凑风格',
    nameEn: 'Compact',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#27ae60',
      '--secondary-color': '#2ecc71',
      '--accent-color': '#16a085',
      '--bg-color': '#ffffff',
      '--bg-color-secondary': '#f0f9f4',
      '--text-color': '#2c3e50',
      '--text-color-secondary': '#7f8c8d',
      '--text-color-placeholder': '#bdc3c7',
      '--border-color': '#d5f4e6',
      '--border-color-light': '#e8f8f5',
      '--shadow': '0 1px 3px 0 rgba(39, 174, 96, 0.1)',
      '--shadow-hover': '0 2px 6px 0 rgba(39, 174, 96, 0.15)',
      '--radius': '6px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'var(--bg-color)',
      '--category-title-scale': '1',
      '--link-grid-columns': 'repeat(auto-fill, minmax(180px, 1fr))',
      '--link-grid-gap': '0.5rem',
      '--link-card-padding': '0.75rem',
      '--link-font-size': '0.9375rem',
      '--link-description-font-size': '0.75rem',
      '--link-content-gap': '0.25rem',
      '--category-font-size': '1.25rem',
      '--category-margin-bottom': '1rem',
      '--link-card-max-width': 'none'
    }
  },

  // ========== 列表风格 ==========
  {
    id: 'list',
    name: '列表风格',
    nameEn: 'List Style',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#8e44ad',
      '--secondary-color': '#9b59b6',
      '--accent-color': '#1abc9c',
      '--bg-color': '#ffffff',
      '--bg-color-secondary': '#f4ecf7',
      '--text-color': '#2c3e50',
      '--text-color-secondary': '#7f8c8d',
      '--text-color-placeholder': '#bdc3c7',
      '--border-color': '#e8daef',
      '--border-color-light': '#f4ecf7',
      '--shadow': '0 1px 3px 0 rgba(142, 68, 173, 0.1)',
      '--shadow-hover': '0 3px 10px 0 rgba(142, 68, 173, 0.2)',
      '--radius': '4px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'var(--bg-color)',
      '--category-title-scale': '1',
      '--link-grid-columns': '1fr',
      '--link-grid-gap': '0.5rem',
      '--link-card-padding': '0.875rem 1rem',
      '--link-font-size': '1rem',
      '--link-description-font-size': '0.875rem',
      '--link-content-gap': '0.25rem',
      '--category-font-size': '1.375rem',
      '--category-margin-bottom': '1.25rem',
      '--link-card-max-width': 'none'
    }
  },

  // ========== 双列风格 ==========
  {
    id: 'two-columns',
    name: '双列风格',
    nameEn: 'Two Columns',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#e74c3c',
      '--secondary-color': '#ec7063',
      '--accent-color': '#f39c12',
      '--bg-color': '#ffffff',
      '--bg-color-secondary': '#fdedec',
      '--text-color': '#2c3e50',
      '--text-color-secondary': '#7f8c8d',
      '--text-color-placeholder': '#bdc3c7',
      '--border-color': '#fadbd8',
      '--border-color-light': '#fdedec',
      '--shadow': '0 3px 12px 0 rgba(231, 76, 60, 0.12)',
      '--shadow-hover': '0 6px 20px 0 rgba(231, 76, 60, 0.2)',
      '--radius': '12px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'var(--bg-color)',
      '--category-title-scale': '1',
      '--link-grid-columns': 'repeat(2, 1fr)',
      '--link-grid-gap': '1.25rem',
      '--link-card-padding': '1.5rem',
      '--link-font-size': '1.125rem',
      '--link-description-font-size': '0.875rem',
      '--link-content-gap': '0.5rem',
      '--category-font-size': '1.5rem',
      '--category-margin-bottom': '1.75rem',
      '--link-card-max-width': 'none'
    }
  },

  // ========== 垂直堆叠风格 ==========
  {
    id: 'vertical-stack',
    name: '垂直堆叠',
    nameEn: 'Vertical Stack',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#f39c12',
      '--secondary-color': '#f1c40f',
      '--accent-color': '#e67e22',
      '--bg-color': '#ffffff',
      '--bg-color-secondary': '#fef9e7',
      '--text-color': '#2c3e50',
      '--text-color-secondary': '#7f8c8d',
      '--text-color-placeholder': '#bdc3c7',
      '--border-color': '#f9e79f',
      '--border-color-light': '#fef9e7',
      '--shadow': '0 2px 8px 0 rgba(243, 156, 18, 0.1)',
      '--shadow-hover': '0 4px 12px 0 rgba(243, 156, 18, 0.18)',
      '--radius': '8px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'var(--bg-color)',
      '--category-title-scale': '1',
      '--link-grid-columns': '1fr',
      '--link-grid-gap': '0.75rem',
      '--link-card-padding': '1rem',
      '--link-font-size': '1.0625rem',
      '--link-description-font-size': '0.8125rem',
      '--link-content-gap': '0.375rem',
      '--category-font-size': '1.3125rem',
      '--category-margin-bottom': '1.25rem',
      '--link-card-max-width': '600px'
    }
  },

  // ========== 大图标风格 ==========
  {
    id: 'large-icons',
    name: '大图标风格',
    nameEn: 'Large Icons',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#1abc9c',
      '--secondary-color': '#16a085',
      '--accent-color': '#3498db',
      '--bg-color': '#ffffff',
      '--bg-color-secondary': '#e8f8f5',
      '--text-color': '#2c3e50',
      '--text-color-secondary': '#7f8c8d',
      '--text-color-placeholder': '#bdc3c7',
      '--border-color': '#a3e4d7',
      '--border-color-light': '#d1f2eb',
      '--shadow': '0 4px 16px 0 rgba(26, 188, 156, 0.15)',
      '--shadow-hover': '0 8px 24px 0 rgba(26, 188, 156, 0.25)',
      '--radius': '20px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-bg': 'var(--bg-color)',
      '--category-title-scale': '1.2',
      '--link-grid-columns': 'repeat(auto-fill, minmax(200px, 1fr))',
      '--link-grid-gap': '1.5rem',
      '--link-card-padding': '2rem',
      '--link-font-size': '1.25rem',
      '--link-description-font-size': '0.9375rem',
      '--link-content-gap': '1rem',
      '--category-font-size': '2rem',
      '--category-margin-bottom': '2.5rem',
      '--link-card-max-width': 'none'
    }
  }
]

