export const defaultSkins = [
  // ========== 经典 — 均衡标准布局，蓝白配色 ==========
  {
    id: 'default',
    name: '经典',
    nameEn: 'Classic',
    preview: '',
    isDefault: true,
    isSystem: true,
    variables: {
      '--primary-color': '#409eff',
      '--secondary-color': '#67c23a',
      '--accent-color': '#e6a23c',
      '--bg-color': '#ffffff',
      '--bg-color-secondary': '#f5f7fa',
      '--text-color': '#303133',
      '--text-color-secondary': '#606266',
      '--text-color-placeholder': '#909399',
      '--border-color': '#dcdfe6',
      '--border-color-light': '#e4e7ed',
      '--shadow': '0 2px 12px 0 rgba(0, 0, 0, 0.1)',
      '--shadow-hover': '0 4px 16px 0 rgba(0, 0, 0, 0.15)',
      '--radius': '8px',
      '--link-grid-columns': 'repeat(auto-fill, minmax(280px, 1fr))',
      '--link-grid-gap': '1rem',
      '--link-card-padding': '1.25rem',
      '--link-card-bg': 'var(--bg-color)',
      '--link-card-max-width': 'none',
      '--link-card-transform': 'translateY(0)',
      '--link-card-hover-transform': 'translateY(-4px) scale(1.02)',
      '--link-font-size': '1.125rem',
      '--link-description-font-size': '0.875rem',
      '--link-description-line-height': '1.4',
      '--link-content-gap': '0.5rem',
      '--category-font-size': '1.5rem',
      '--category-margin-bottom': '1.5rem',
      '--category-title-scale': '1',
      '--backdrop-filter': 'none'
    }
  },

  // ========== 深色 — 经典暗色模式 ==========
  {
    id: 'dark',
    name: '深色',
    nameEn: 'Dark',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#409eff',
      '--secondary-color': '#67c23a',
      '--accent-color': '#e6a23c',
      '--bg-color': '#1d1e1f',
      '--bg-color-secondary': '#141414',
      '--text-color': '#e5eaf3',
      '--text-color-secondary': '#cfd3dc',
      '--text-color-placeholder': '#909399',
      '--border-color': '#4c4d4f',
      '--border-color-light': '#363637',
      '--shadow': '0 2px 12px 0 rgba(0, 0, 0, 0.3)',
      '--shadow-hover': '0 4px 16px 0 rgba(0, 0, 0, 0.4)',
      '--radius': '8px',
      '--link-grid-columns': 'repeat(auto-fill, minmax(280px, 1fr))',
      '--link-grid-gap': '1rem',
      '--link-card-padding': '1.25rem',
      '--link-card-bg': '#1d1e1f',
      '--link-card-max-width': 'none',
      '--link-card-transform': 'translateY(0)',
      '--link-card-hover-transform': 'translateY(-4px) scale(1.02)',
      '--link-font-size': '1.125rem',
      '--link-description-font-size': '0.875rem',
      '--link-description-line-height': '1.4',
      '--link-content-gap': '0.5rem',
      '--category-font-size': '1.5rem',
      '--category-margin-bottom': '1.5rem',
      '--category-title-scale': '1',
      '--backdrop-filter': 'none'
    }
  },

  // ========== 玻璃态 — 毛玻璃漂浮卡片，超大圆角，呼吸感间距 ==========
  {
    id: 'glass',
    name: '玻璃态',
    nameEn: 'Glass',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#00cec9',
      '--secondary-color': '#81ecec',
      '--accent-color': '#55efc4',
      '--bg-color': 'rgba(255, 255, 255, 0.7)',
      '--bg-color-secondary': 'rgba(240, 248, 255, 0.6)',
      '--text-color': '#2d3436',
      '--text-color-secondary': '#636e72',
      '--text-color-placeholder': '#b2bec3',
      '--border-color': 'rgba(255, 255, 255, 0.35)',
      '--border-color-light': 'rgba(255, 255, 255, 0.2)',
      '--shadow': '0 8px 32px 0 rgba(0, 206, 201, 0.12)',
      '--shadow-hover': '0 16px 48px 0 rgba(0, 206, 201, 0.25)',
      '--radius': '24px',
      '--link-grid-columns': 'repeat(auto-fill, minmax(300px, 1fr))',
      '--link-grid-gap': '1.5rem',
      '--link-card-padding': '1.75rem',
      '--link-card-bg': 'rgba(255, 255, 255, 0.35)',
      '--link-card-max-width': 'none',
      '--link-card-transform': 'translateY(0)',
      '--link-card-hover-transform': 'translateY(-6px) scale(1.03)',
      '--link-font-size': '1.125rem',
      '--link-description-font-size': '0.9rem',
      '--link-description-line-height': '1.5',
      '--link-content-gap': '0.625rem',
      '--category-font-size': '1.75rem',
      '--category-margin-bottom': '1.75rem',
      '--category-title-scale': '1',
      '--backdrop-filter': 'blur(12px) saturate(180%)'
    }
  },

  // ========== 赛博朋克 — 霓虹密集终端风，尖锐直角，紧凑排列 ==========
  {
    id: 'cyberpunk',
    name: '赛博朋克',
    nameEn: 'Cyberpunk',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#00ff41',
      '--secondary-color': '#00d9ff',
      '--accent-color': '#ff0055',
      '--bg-color': '#0a0a0a',
      '--bg-color-secondary': '#050505',
      '--text-color': '#00ff41',
      '--text-color-secondary': '#00d9ff',
      '--text-color-placeholder': '#444444',
      '--border-color': '#00ff41',
      '--border-color-light': '#0a3d0f',
      '--shadow': '0 0 8px rgba(0, 255, 65, 0.3), inset 0 0 8px rgba(0, 255, 65, 0.05)',
      '--shadow-hover': '0 0 20px rgba(0, 255, 65, 0.6), 0 0 40px rgba(0, 255, 65, 0.2)',
      '--radius': '0px',
      '--link-grid-columns': 'repeat(auto-fill, minmax(200px, 1fr))',
      '--link-grid-gap': '0.5rem',
      '--link-card-padding': '0.875rem',
      '--link-card-bg': '#0f0f0f',
      '--link-card-max-width': 'none',
      '--link-card-transform': 'translateY(0)',
      '--link-card-hover-transform': 'translateY(0) scale(1)',
      '--link-font-size': '0.9375rem',
      '--link-description-font-size': '0.75rem',
      '--link-description-line-height': '1.3',
      '--link-content-gap': '0.25rem',
      '--category-font-size': '1.125rem',
      '--category-margin-bottom': '0.75rem',
      '--category-title-scale': '1',
      '--backdrop-filter': 'none'
    }
  },

  // ========== 北欧 — 冷静蓝灰，宽松间距，大卡片，舒适阅读 ==========
  {
    id: 'nord',
    name: '北欧极光',
    nameEn: 'Nord',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#88c0d0',
      '--secondary-color': '#81a1c1',
      '--accent-color': '#ebcb8b',
      '--bg-color': '#2e3440',
      '--bg-color-secondary': '#272c36',
      '--text-color': '#eceff4',
      '--text-color-secondary': '#d8dee9',
      '--text-color-placeholder': '#616e88',
      '--border-color': '#4c566a',
      '--border-color-light': '#3b4252',
      '--shadow': '0 2px 8px 0 rgba(0, 0, 0, 0.2)',
      '--shadow-hover': '0 6px 20px 0 rgba(136, 192, 208, 0.15)',
      '--radius': '12px',
      '--link-grid-columns': 'repeat(auto-fill, minmax(320px, 1fr))',
      '--link-grid-gap': '1.75rem',
      '--link-card-padding': '1.75rem',
      '--link-card-bg': '#3b4252',
      '--link-card-max-width': 'none',
      '--link-card-transform': 'translateY(0)',
      '--link-card-hover-transform': 'translateY(-2px)',
      '--link-font-size': '1.1875rem',
      '--link-description-font-size': '0.9375rem',
      '--link-description-line-height': '1.6',
      '--link-content-gap': '0.625rem',
      '--category-font-size': '1.625rem',
      '--category-margin-bottom': '1.75rem',
      '--category-title-scale': '1',
      '--backdrop-filter': 'none'
    }
  },

  // ========== 暗夜紫 — Dracula 深紫暗色，紫光 hover ==========
  {
    id: 'dracula',
    name: '暗夜紫',
    nameEn: 'Dracula',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#bd93f9',
      '--secondary-color': '#ff79c6',
      '--accent-color': '#50fa7b',
      '--bg-color': '#282a36',
      '--bg-color-secondary': '#1e1f29',
      '--text-color': '#f8f8f2',
      '--text-color-secondary': '#c0c0c8',
      '--text-color-placeholder': '#6272a4',
      '--border-color': '#44475a',
      '--border-color-light': '#363949',
      '--shadow': '0 4px 14px 0 rgba(0, 0, 0, 0.35)',
      '--shadow-hover': '0 8px 28px 0 rgba(189, 147, 249, 0.2)',
      '--radius': '12px',
      '--link-grid-columns': 'repeat(auto-fill, minmax(280px, 1fr))',
      '--link-grid-gap': '1.125rem',
      '--link-card-padding': '1.375rem',
      '--link-card-bg': '#21222c',
      '--link-card-max-width': 'none',
      '--link-card-transform': 'translateY(0)',
      '--link-card-hover-transform': 'translateY(-4px) scale(1.02)',
      '--link-font-size': '1.125rem',
      '--link-description-font-size': '0.875rem',
      '--link-description-line-height': '1.4',
      '--link-content-gap': '0.5rem',
      '--category-font-size': '1.5rem',
      '--category-margin-bottom': '1.5rem',
      '--category-title-scale': '1',
      '--backdrop-filter': 'none'
    }
  },

  // ========== 樱花 — 甜美粉色，超圆角，弹跳 hover，活泼排版 ==========
  {
    id: 'sakura',
    name: '樱花',
    nameEn: 'Sakura',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#ec4899',
      '--secondary-color': '#f472b6',
      '--accent-color': '#a855f7',
      '--bg-color': '#fdf2f8',
      '--bg-color-secondary': '#fce7f3',
      '--text-color': '#831843',
      '--text-color-secondary': '#9d174d',
      '--text-color-placeholder': '#d4a0b9',
      '--border-color': '#fbcfe8',
      '--border-color-light': '#fce7f3',
      '--shadow': '0 4px 20px 0 rgba(236, 72, 153, 0.1)',
      '--shadow-hover': '0 12px 32px 0 rgba(236, 72, 153, 0.2)',
      '--radius': '20px',
      '--link-grid-columns': 'repeat(auto-fill, minmax(240px, 1fr))',
      '--link-grid-gap': '1.25rem',
      '--link-card-padding': '1.5rem',
      '--link-card-bg': '#ffffff',
      '--link-card-max-width': 'none',
      '--link-card-transform': 'translateY(0)',
      '--link-card-hover-transform': 'translateY(-8px) scale(1.05)',
      '--link-font-size': '1.0625rem',
      '--link-description-font-size': '0.9rem',
      '--link-description-line-height': '1.5',
      '--link-content-gap': '0.5rem',
      '--category-font-size': '1.75rem',
      '--category-margin-bottom': '1.5rem',
      '--category-title-scale': '1.05',
      '--backdrop-filter': 'none'
    }
  },

  // ========== 杂志 — 大卡片双列，大字号，社论排版 ==========
  {
    id: 'magazine',
    name: '杂志',
    nameEn: 'Magazine',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#1a1a1a',
      '--secondary-color': '#c0392b',
      '--accent-color': '#e74c3c',
      '--bg-color': '#faf9f6',
      '--bg-color-secondary': '#f2f0eb',
      '--text-color': '#1a1a1a',
      '--text-color-secondary': '#555555',
      '--text-color-placeholder': '#aaaaaa',
      '--border-color': '#e0ddd5',
      '--border-color-light': '#eae7e0',
      '--shadow': '0 1px 3px 0 rgba(0, 0, 0, 0.06)',
      '--shadow-hover': '0 6px 24px 0 rgba(0, 0, 0, 0.1)',
      '--radius': '4px',
      '--link-grid-columns': 'repeat(2, 1fr)',
      '--link-grid-gap': '2rem',
      '--link-card-padding': '2.5rem',
      '--link-card-bg': '#ffffff',
      '--link-card-max-width': 'none',
      '--link-card-transform': 'translateY(0)',
      '--link-card-hover-transform': 'translateY(-3px)',
      '--link-font-size': '1.5rem',
      '--link-description-font-size': '1rem',
      '--link-description-line-height': '1.7',
      '--link-content-gap': '0.75rem',
      '--category-font-size': '2rem',
      '--category-margin-bottom': '2rem',
      '--category-title-scale': '1',
      '--backdrop-filter': 'none'
    }
  },

  // ========== 终端 — 单列列表式，琥珀色暗底，极窄间距 ==========
  {
    id: 'terminal',
    name: '终端',
    nameEn: 'Terminal',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#ffb300',
      '--secondary-color': '#ff8f00',
      '--accent-color': '#76ff03',
      '--bg-color': '#1a1a1a',
      '--bg-color-secondary': '#111111',
      '--text-color': '#ffb300',
      '--text-color-secondary': '#cc8f00',
      '--text-color-placeholder': '#554400',
      '--border-color': '#3d2e00',
      '--border-color-light': '#2a2000',
      '--shadow': 'none',
      '--shadow-hover': '0 0 12px rgba(255, 179, 0, 0.2)',
      '--radius': '2px',
      '--link-grid-columns': '1fr',
      '--link-grid-gap': '0.375rem',
      '--link-card-padding': '0.75rem 1rem',
      '--link-card-bg': '#1e1e1e',
      '--link-card-max-width': '700px',
      '--link-card-transform': 'translateY(0)',
      '--link-card-hover-transform': 'translateY(0) scale(1)',
      '--link-font-size': '0.9375rem',
      '--link-description-font-size': '0.8125rem',
      '--link-description-line-height': '1.3',
      '--link-content-gap': '0.25rem',
      '--category-font-size': '1.125rem',
      '--category-margin-bottom': '0.625rem',
      '--category-title-scale': '1',
      '--backdrop-filter': 'none'
    }
  },

  // ========== 马赛克 — 密集小卡片网格，一屏尽览 ==========
  {
    id: 'mosaic',
    name: '马赛克',
    nameEn: 'Mosaic',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#6366f1',
      '--secondary-color': '#8b5cf6',
      '--accent-color': '#ec4899',
      '--bg-color': '#ffffff',
      '--bg-color-secondary': '#f8fafc',
      '--text-color': '#1e293b',
      '--text-color-secondary': '#64748b',
      '--text-color-placeholder': '#94a3b8',
      '--border-color': '#e2e8f0',
      '--border-color-light': '#f1f5f9',
      '--shadow': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      '--shadow-hover': '0 4px 12px 0 rgba(99, 102, 241, 0.15)',
      '--radius': '6px',
      '--link-grid-columns': 'repeat(auto-fill, minmax(155px, 1fr))',
      '--link-grid-gap': '0.5rem',
      '--link-card-padding': '0.75rem',
      '--link-card-bg': '#ffffff',
      '--link-card-max-width': 'none',
      '--link-card-transform': 'scale(1)',
      '--link-card-hover-transform': 'scale(1.08)',
      '--link-font-size': '0.8125rem',
      '--link-description-font-size': '0.6875rem',
      '--link-description-line-height': '1.3',
      '--link-content-gap': '0.1875rem',
      '--category-font-size': '1.125rem',
      '--category-margin-bottom': '0.75rem',
      '--category-title-scale': '1',
      '--backdrop-filter': 'none'
    }
  },

  // ========== 粗犷 — 无圆角无阴影，粗边框，大胆排版 ==========
  {
    id: 'brutalist',
    name: '粗犷',
    nameEn: 'Brutalist',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#000000',
      '--secondary-color': '#ff0000',
      '--accent-color': '#0000ff',
      '--bg-color': '#ffffff',
      '--bg-color-secondary': '#ffffff',
      '--text-color': '#000000',
      '--text-color-secondary': '#333333',
      '--text-color-placeholder': '#999999',
      '--border-color': '#000000',
      '--border-color-light': '#000000',
      '--shadow': 'none',
      '--shadow-hover': '4px 4px 0px #000000',
      '--radius': '0px',
      '--link-grid-columns': 'repeat(auto-fill, minmax(280px, 1fr))',
      '--link-grid-gap': '0px',
      '--link-card-padding': '1.5rem',
      '--link-card-bg': '#ffffff',
      '--link-card-max-width': 'none',
      '--link-card-transform': 'translate(0, 0)',
      '--link-card-hover-transform': 'translate(-4px, -4px)',
      '--link-font-size': '1.375rem',
      '--link-description-font-size': '0.875rem',
      '--link-description-line-height': '1.4',
      '--link-content-gap': '0.375rem',
      '--category-font-size': '2.25rem',
      '--category-margin-bottom': '1rem',
      '--category-title-scale': '1',
      '--backdrop-filter': 'none'
    }
  },

  // ========== 禅 — 极简留白，超大圆角，隐形卡片，呼吸感 ==========
  {
    id: 'zen',
    name: '禅',
    nameEn: 'Zen',
    preview: '',
    isDefault: false,
    isSystem: true,
    variables: {
      '--primary-color': '#8b9da7',
      '--secondary-color': '#a3b5bf',
      '--accent-color': '#c4a882',
      '--bg-color': '#fafaf8',
      '--bg-color-secondary': '#f5f5f0',
      '--text-color': '#4a4a45',
      '--text-color-secondary': '#8a8a82',
      '--text-color-placeholder': '#c0c0b8',
      '--border-color': '#eeede8',
      '--border-color-light': '#f5f5f0',
      '--shadow': '0 1px 4px 0 rgba(0, 0, 0, 0.03)',
      '--shadow-hover': '0 2px 8px 0 rgba(0, 0, 0, 0.06)',
      '--radius': '32px',
      '--link-grid-columns': 'repeat(auto-fill, minmax(360px, 1fr))',
      '--link-grid-gap': '2.5rem',
      '--link-card-padding': '2rem 2.25rem',
      '--link-card-bg': 'transparent',
      '--link-card-max-width': 'none',
      '--link-card-transform': 'translateY(0)',
      '--link-card-hover-transform': 'translateY(-1px)',
      '--link-font-size': '1.1875rem',
      '--link-description-font-size': '0.9375rem',
      '--link-description-line-height': '1.8',
      '--link-content-gap': '0.75rem',
      '--category-font-size': '1.375rem',
      '--category-margin-bottom': '2.5rem',
      '--category-title-scale': '1',
      '--backdrop-filter': 'none'
    }
  }
]
